"""Build the public 1000-text corpus for kleinhirn tests and goldens.

500 strings come from the argmin content tree (CC-BY-4.0, attribution in
NOTICE), 500 come from tools/synthetic_texts.py (our own generator).
The argmin pool is collected from content/families (top-level JSON
files): every string field of every case, then a deterministic seed-0
sample across three buckets (German prose, code lines, formula
strings), filled up with prose when a bucket runs short.

Usage:
    python3 tools/build_corpus.py --argmin /path/to/argmin/content \
        [--out tests/corpus/texts1000.json]

The output file is committed; --argmin is only needed to regenerate it.
"""
import argparse
import json
import random
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from synthetic_texts import synthetic_texts  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
WS_RE = re.compile(r"\s+")

# Formula characters: super/subscripts, roots, operators, greek letters.
FORMULA_CHARS = set("²³¹⁰⁴⁵⁶⁷⁸⁹ⁿ₀₁₂₃₄₅₆₇₈₉√∛∜∑∏∫∮≈≠≤≥±×÷·∙∞∂∇∈∉⊂⊃∪∩∧∨¬∀∃→←↔⇒⇐⇔°′″π")
FORMULA_CHARS.update(chr(c) for c in range(0x0391, 0x03AA))
FORMULA_CHARS.update(chr(c) for c in range(0x03B1, 0x03CA))

CODE_HINT = re.compile(
    r"^(def |class |import |from |for |while |if |elif |else:|return |"
    r"print\(|raise |const |let |var |function |=>|\s)")


def iter_strings(o):
    if isinstance(o, str):
        yield o
    elif isinstance(o, dict):
        for v in o.values():
            yield from iter_strings(v)
    elif isinstance(o, list):
        for v in o:
            yield from iter_strings(v)


def argmin_pool(argmin_content: Path) -> dict[str, list[str]]:
    german, code, formula = set(), set(), set()
    for pool in ("families",):
        for path in sorted((argmin_content / pool).glob("*.json")):
            for raw in iter_strings(json.loads(path.read_text())):
                for line in raw.splitlines():
                    s = WS_RE.sub(" ", line).strip()
                    if len(s) < 8:
                        continue
                    if any(ch in FORMULA_CHARS for ch in s):
                        formula.add(s)
                    elif CODE_HINT.match(line) or s.startswith(("(", "[")):
                        code.add(s)
                    else:
                        german.add(s)
    return {"german": sorted(german), "code": sorted(code),
            "formula": sorted(formula)}


def build(argmin_content: Path, n_argmin: int = 500) -> dict:
    pool = argmin_pool(argmin_content)
    rng = random.Random(0)
    per_bucket = n_argmin // 3
    picks = []
    for name in ("german", "code", "formula"):
        picks.extend(rng.sample(pool[name], min(per_bucket, len(pool[name]))))
    # Fill the remainder from the largest remaining pool (prose first).
    if len(picks) < n_argmin:
        rest = [s for name in ("german", "code", "formula")
                for s in pool[name] if s not in set(picks)]
        picks.extend(rest[: n_argmin - len(picks)])
    synthetic = synthetic_texts()
    texts = picks[:n_argmin] + synthetic
    return {
        "schema": "kleinhirn-corpus-v1",
        "count": len(texts),
        "license": {
            "argmin": "CC-BY-4.0 (see NOTICE)",
            "synthetic": "generated by tools/synthetic_texts.py",
        },
        "argmin": picks[:n_argmin],
        "synthetic": synthetic,
        "texts": texts,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--argmin", type=Path, required=True,
                    help="path to argmin/content (read-only)")
    ap.add_argument("--out", type=Path, default=ROOT / "tests/corpus/texts1000.json")
    args = ap.parse_args()
    doc = build(args.argmin)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, ensure_ascii=False, indent=1))
    print(f"corpus: {doc['count']} texts "
          f"(argmin {len(doc['argmin'])}, synthetic {len(doc['synthetic'])}) "
          f"-> {args.out}")


if __name__ == "__main__":
    main()
